### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by coder1165** [thuml/Anomaly-Transformer#71]
When run code " bash ./scripts/MSL.sh" raised error:
 Traceback (most recent call last):
  File "main.py", line 52, in <module>
    main(config)
  File "main.py", line 18, in main
    solver = Solver(vars(config))
  File "/storage/student1/c_cxl/cxl/Anomaly-Transformer/solver.py", line 85, in __init__
    self.build_model()
  File "/storage/student1/c_cxl/cxl/Anomaly-Transformer/solver.py", line 90, in build_model
    self.model = AnomalyTransformer(win_size=self.win_size, enc_in=self.input_c, c_out=self.output_c, e_layers=3)
  File "/storage/student1/c_cxl/cxl/Anomaly-Transformer/model/AnomalyTransformer.py", line 77, in __init__
    ) for l in range(e_layers)
  File "/storage/student1/c_cxl/cxl/Anomaly-Transformer/model/AnomalyTransformer.py", line 77, in <listcomp>
    ) for l in range(e_layers)
  File "/storage/student1/c_cxl/cxl/Anomaly-Transformer/model/attn.py", line 29, in __init__
    self.distances = torch.zeros((window_size, window_size)).cuda()
  File "/storage/student1/c_cxl/miniconda3/envs/Anomaly_Trans/lib/python3.6/site-packages/torch/cuda/__init__.py", line 214, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by Zhenxiaoan** [comment]
I already checked pytorch's version,use 
import torch
print(torch.cuda.device_count())#1
torch.cuda.is_available()#True

**Comment by coder1165** [comment]
Sorry,I figure it out. Pytorch's version is wrong.

**Comment by JeSciglio** [comment]
> Sorry,I figure it out. Pytorch's version is wrong.

I meet the same mistake.Pytorch version is 1.8.0,cuda 10.2,python 3.6
I cannot figure it out.How did you solve it?

**Comment by Victor-KKKK** [comment]
I also have this issue when using google Colab.
If anyone knows a solution, please let me know it.
